services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4567:4567"
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./:/app
      - bundle_cache:/usr/local/bundle
    stdin_open: true
    tty: true

volumes:
  bundle_cache: